XSLT: no direct create for non-addressable entity sets
oasis-tcs/odata-openapi pull request #312
Opened 2024-10-10 09:48 UTC by ralfhandl

Part of #311

2024-10-17 11:44 UTC, ralfhandl commented
@sterlp Can you please check if this is what you expect?

Note: I made the `AddressSet` creatable, updatable, and deletable to cover all cases.

https://github.com/oasis-tcs/odata-openapi/blob/c0f90b28112b6f6545e2af7152c15a4e2afa0fcc/tools/tests/addressable-v2.xml#L102-L103

2024-10-18 07:01 UTC, HeikoTheissen commented
Why does `/HeadSet('{BusinessPartner}')/to_Address` appear for both `HeadSet` and `AddressSet` in Swagger?

`AddressSet` appears for `PATCH` and `DELETE`, but not for `GET` and `POST` (although it is creatable). Is that really what `sap:addressable="false"` means?

2024-10-18 08:00 UTC, ralfhandl commented
> Why does `/HeadSet('{BusinessPartner}')/to_Address` appear for both `HeadSet` and `AddressSet` in Swagger?

Each operation is tagged with both the source and the target entity set, and in this case the two are different.

The same happens for example here:
* https://api.sap.com/api/CE_SALESORDER_0001/resource/Sales_Order_Header
* https://api.sap.com/api/CE_SALESORDER_0001/resource/Sales_Order_Item

2024-10-18 08:24 UTC, HeikoTheissen commented
> `AddressSet` appears for `PATCH` and `DELETE`, but not for `GET` and `POST` (although it is creatable). Is that really what `sap:addressable="false"` means?

Is the following reasoning correct?

Non-addressability removes the `GET /AddressSet` and `POST /AddressSet`, because there are the alternatives `GET /HeadSet(...)/to_Address` and `POST /GET HeadSet(...)/to_Address`. But there are no alternatives for `PATCH` and `DELETE`, so these remain.

If should be different if `to_Address` was a containment navigation property. But even if I add 
```xml
<NavigationProperty Name="to_Address" Relationship="ZE_API_DEMO_SRV.to_Address"
          FromRole="FromRole_to_Address" ToRole="ToRole_to_Address" sap:containstarget="true" />
```
the `PATCH /AddressSet(...)` and `DELETE /AddressSet(...)` remain in Swagger. I would have expected them to be converted to `PATCH /HeadSet(...)/to_Address(...)` and `DELETE /HeadSet(...)/to_Address(...)`.

2024-10-18 11:40 UTC, HeikoTheissen requested changes
**Wrong Swagger output for containment navigation properties**

If I add 
```xml
<NavigationProperty Name="to_Address" Relationship="ZE_API_DEMO_SRV.to_Address"
          FromRole="FromRole_to_Address" ToRole="ToRole_to_Address" sap:containstarget="true" />
```
then Swagger contains

**HeadSet**
- `PATCH /HeadSet(...)/to_Address(...)`
- `DELETE /HeadSet(...)/to_Address(...)`

**AddressSet**
- `PATCH /AddressSet(...)`
- `DELETE /AddressSet(...)`

The resource paths given for AddressSet are invalid, they must equal the resource paths given for HeadSet.

2024-10-18 14:55 UTC, ralfhandl commented
> If should be different if `to_Address` was a containment navigation property.

Correct, and in OData V4 we use containment. In OData V2 there is no such thing.

2024-10-18 15:16 UTC, HeikoTheissen approved these changes

2024-10-18 15:21 UTC, merged